name: Android Release APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-prod-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Secrets (Keystore & local.properties)
      run: |
        echo "LASTFM_API_KEY=${{ secrets.LASTFM_API_KEY }}" > local.properties
        echo "LASTFM_SECRET=${{ secrets.LASTFM_SECRET }}" >> local.properties

        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > bitchord-release.jks
        {
          echo "storeFile=bitchord-release.jks"
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}"
          echo "keyAlias=${{ secrets.KEY_ALIAS }}"
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}"
        } > keystore.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Signed Prod Release APK
      run: ./gradlew assembleProdDebug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bitchord-prod-release-signed
        path: app/build/outputs/apk/**/*.apk
